# Generated by Django 3.2 on 2021-12-16 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0002_news_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='desc_10',
            field=models.TextField(default='SOME STRING'),
        ),
        migrations.AddField(
            model_name='news',
            name='desc_11',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='desc_12',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='desc_13',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='desc_3',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='desc_4',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='desc_5',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='desc_6',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='desc_7',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='desc_8',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='desc_9',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_11',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_12',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_13',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AddField(
            model_name='news',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='parent_image',
            field=models.ImageField(default='SOME STRING', upload_to='home/images'),
        ),
    ]
