# Generated by Django 3.2 on 2021-12-16 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0004_auto_20211215_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='countryname',
            field=models.ManyToManyField(blank=True, null=True, to='CosmosivicsaApplication.CountryName'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsname',
            field=models.ManyToManyField(blank=True, null=True, to='CosmosivicsaApplication.NewsType'),
        ),
        migrations.AlterField(
            model_name='news',
            name='parent_image',
            field=models.ImageField(upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
