# Generated by Django 3.2 on 2021-12-17 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0006_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name_plural': 'Post'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='name',
        ),
    ]
