# Generated by Django 3.2 on 2021-12-17 06:16

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0007_auto_20211216_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='text',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
