# Generated by Django 3.2 on 2021-12-17 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0008_alter_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='textr',
        ),
    ]
