# Generated by Django 3.2 on 2021-12-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0012_market_postimage_project_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc_1',
            field=models.CharField(default=1, max_length=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='desc_2',
            field=models.CharField(default=1, max_length=3001),
            preserve_default=False,
        ),
    ]
