# Generated by Django 3.2 on 2021-12-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0013_auto_20211217_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
