# Generated by Django 3.2 on 2021-12-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0014_project_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='multipleimages',
            new_name='parent_images',
        ),
        migrations.AlterField(
            model_name='postimage',
            name='images',
            field=models.ImageField(upload_to='home/images'),
        ),
    ]
