# Generated by Django 3.2 on 2021-12-17 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0015_auto_20211217_0519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imag', to='CosmosivicsaApplication.project'),
        ),
    ]
