# Generated by Django 3.2 on 2021-12-17 19:11

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0016_alter_postimage_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParagraphAndImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('paragraph', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='home/images')),
                ('projectFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagg', to='CosmosivicsaApplication.project')),
            ],
        ),
    ]
