# Generated by Django 3.2 on 2021-12-18 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0017_paragraphandimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_10',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_11',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_12',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_13',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_4',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_5',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_6',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_7',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_8',
        ),
        migrations.RemoveField(
            model_name='news',
            name='desc_9',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_11',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_12',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_13',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='news',
            name='image_9',
        ),
        migrations.AddField(
            model_name='paragraphandimage',
            name='newsFK',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='imaggg', to='CosmosivicsaApplication.news'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='paragraphandimage',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
