# Generated by Django 3.2 on 2021-12-18 08:16

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0018_auto_20211217_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsParagraphAndImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='home/images')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectParagraphAndImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('paragraph', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='home/images')),
                ('projectFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagg', to='CosmosivicsaApplication.project')),
            ],
        ),
        migrations.RenameModel(
            old_name='PostImage',
            new_name='ProjectPostImage',
        ),
        migrations.AlterField(
            model_name='news',
            name='countryname',
            field=models.ManyToManyField(to='CosmosivicsaApplication.CountryName'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsname',
            field=models.ManyToManyField(to='CosmosivicsaApplication.NewsType'),
        ),
        migrations.DeleteModel(
            name='ParagraphAndImage',
        ),
        migrations.AddField(
            model_name='newsparagraphandimage',
            name='newsFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagge', to='CosmosivicsaApplication.news'),
        ),
    ]
