# Generated by Django 3.2 on 2021-12-18 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0019_auto_20211218_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='countryname',
            field=models.ManyToManyField(blank=True, null=True, to='CosmosivicsaApplication.CountryName'),
        ),
        migrations.AlterField(
            model_name='news',
            name='newsname',
            field=models.ManyToManyField(blank=True, null=True, to='CosmosivicsaApplication.NewsType'),
        ),
        migrations.AlterField(
            model_name='project',
            name='marketname',
            field=models.ManyToManyField(blank=True, null=True, to='CosmosivicsaApplication.Market'),
        ),
        migrations.AlterField(
            model_name='project',
            name='servicename',
            field=models.ManyToManyField(blank=True, null=True, to='CosmosivicsaApplication.Service'),
        ),
    ]
