# Generated by Django 3.2 on 2021-12-18 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0022_auto_20211218_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='key_highlights',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sustainability',
            field=models.CharField(blank=True, max_length=900, null=True),
        ),
    ]
