# Generated by Django 3.2 on 2021-12-19 11:54

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0023_auto_20211218_0534'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publish_job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=1000)),
                ('job_category', models.CharField(max_length=1001)),
                ('business_line', models.CharField(max_length=1002)),
                ('requirements', ckeditor_uploader.fields.RichTextUploadingField()),
                ('responsibiltie', ckeditor_uploader.fields.RichTextUploadingField()),
                ('country', models.CharField(max_length=1000)),
                ('position_status', models.CharField(max_length=1000)),
                ('requisition_vacancy_no', models.CharField(max_length=1000)),
            ],
        ),
    ]
