# Generated by Django 3.2 on 2021-12-19 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0024_publish_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publish_job',
            name='requisition_vacancy_no',
            field=models.IntegerField(max_length=1000),
        ),
    ]
