# Generated by Django 3.2 on 2021-12-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0026_auto_20211219_0401'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=300)),
                ('province', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
                ('institution_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('institution_graduation_year', models.CharField(blank=True, max_length=1000, null=True)),
                ('degree_name', models.CharField(blank=True, max_length=500, null=True)),
                ('major_area', models.CharField(blank=True, max_length=5000, null=True)),
                ('company_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('start_job_year', models.CharField(blank=True, max_length=100, null=True)),
                ('end_job_year', models.CharField(blank=True, max_length=100, null=True)),
                ('responsibilties', models.TextField()),
            ],
        ),
    ]
