# Generated by Django 3.2 on 2021-12-19 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0028_newstype_newnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='newser',
            field=models.CharField(default=1, max_length=1001),
            preserve_default=False,
        ),
    ]
