# Generated by Django 3.2 on 2021-12-19 22:45

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0029_service_newser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='newser',
            new_name='main_title',
        ),
        migrations.RemoveField(
            model_name='newstype',
            name='newnews',
        ),
        migrations.AddField(
            model_name='service',
            name='service_images',
            field=models.ImageField(default=1, upload_to='home/images'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ServiceParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('paragraph', ckeditor_uploader.fields.RichTextUploadingField()),
                ('projectFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicefk', to='CosmosivicsaApplication.newstype')),
            ],
        ),
    ]
