# Generated by Django 3.2 on 2021-12-19 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0030_auto_20211219_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceparagraph',
            name='projectFK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicefk', to='CosmosivicsaApplication.service'),
        ),
    ]
