# Generated by Django 3.2 on 2021-12-20 09:32

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0032_auto_20211220_0120'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='main_title',
            field=models.CharField(default=1, max_length=1001),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='market',
            name='market_images',
            field=models.ImageField(default=1, upload_to='home/images'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='MarketParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=300, null=True)),
                ('paragraph', ckeditor_uploader.fields.RichTextUploadingField()),
                ('projectFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketfk', to='CosmosivicsaApplication.market')),
            ],
        ),
    ]
