# Generated by Django 3.2 on 2021-12-20 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0033_auto_20211220_0132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_Page_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='home/images')),
            ],
        ),
        migrations.CreateModel(
            name='Home_Page_Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_content', models.CharField(blank=True, max_length=3000, null=True)),
                ('videofile', models.FileField(null=True, upload_to='home/SliderVideos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
            ],
        ),
    ]
