# Generated by Django 3.2 on 2021-12-20 18:04

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0034_home_page_images_home_page_videos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_Firm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='home/SliderVideos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Our_Values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(null=True, upload_to='home/SliderVideos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])])),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Our_ValuesParagraphAndImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('paragraph', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='home/images')),
                ('valuesFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='CosmosivicsaApplication.our_values')),
            ],
        ),
        migrations.CreateModel(
            name='Our_FirmParagraphAndImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('paragraph', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='home/images')),
                ('firmFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='firm', to='CosmosivicsaApplication.our_firm')),
            ],
        ),
    ]
