# Generated by Django 3.2 on 2021-12-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0036_our_firm_excecutive_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_firm_excecutive_images',
            name='about',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='our_firm_excecutive_images',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='our_firm_excecutive_images',
            name='work',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
