# Generated by Django 3.2 on 2021-12-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0038_our_offices'),
    ]

    operations = [
        migrations.CreateModel(
            name='press_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('project', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_options', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.TextField()),
                ('message_file', models.ImageField(upload_to='home/images')),
            ],
        ),
    ]
