# Generated by Django 3.2 on 2021-12-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0039_press_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academic_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acedemic', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('acedemic_ins', models.CharField(max_length=500)),
                ('degree', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('project', models.CharField(blank=True, max_length=1000, null=True)),
                ('project_options', models.CharField(blank=True, max_length=1000, null=True)),
                ('message', models.TextField()),
                ('message_file', models.ImageField(upload_to='home/images')),
            ],
        ),
    ]
