# Generated by Django 3.2 on 2021-12-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0041_auto_20211221_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business_Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('office_name', models.CharField(max_length=1000)),
                ('message', models.TextField()),
                ('message_file', models.FileField(upload_to='home/images')),
                ('sell_product', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
