# Generated by Django 3.2 on 2021-12-21 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0043_auto_20211221_0612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='others_contact',
            name='company',
        ),
    ]
