# Generated by Django 3.2 on 2021-12-22 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0045_auto_20211221_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academic_contact',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='business_contact',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='career_contact',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='others_contact',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='press_contact',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='home/images'),
        ),
    ]
