# Generated by Django 3.2 on 2021-12-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0046_auto_20211221_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press_contact',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='press_contact',
            name='message_file',
            field=models.FileField(null=True, upload_to='home/images'),
        ),
    ]
