# Generated by Django 3.2 on 2021-12-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0047_auto_20211221_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business_contact',
            name='company',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='career_contact',
            name='job_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='career_contact',
            name='message_file',
            field=models.FileField(null=True, upload_to='home/images'),
        ),
        migrations.AlterField(
            model_name='career_contact',
            name='url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='press_contact',
            name='message_file',
            field=models.FileField(blank=True, null=True, upload_to='home/images'),
        ),
    ]
