# Generated by Django 4.0.1 on 2022-01-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CosmosivicsaApplication', '0048_auto_20211221_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='press_contact',
            name='message_file',
            field=models.FileField(null=True, upload_to='home/images'),
        ),
    ]
